---
- name: Deploy Application
  hosts: target_node
  become: yes
  tasks:
    - name: Create application directory
      file:
        path: /opt/multi-container-service
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'

    - name: Copy application files
      synchronize:
        src: ~/multi-container-service/
        dest: /opt/multi-container-service/
        delete: yes
        recursive: yes
      delegate_to: control_node

    - name: Set proper permissions
      file:
        path: /opt/multi-container-service
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        recurse: yes

    - name: Pull latest Docker images
      docker_compose:
        project_src: /opt/multi-container-service
        pull: yes
        state: present

    - name: Start application
      docker_compose:
        project_src: /opt/multi-container-service
        state: present
        restarted: yes

    - name: Wait for application to be ready
      uri:
        url: http://localhost/health
        return_content: yes
      register: health_check
      until: health_check.status == 200
      retries: 12
      delay: 5

    - name: Verify deployment
      debug:
        msg: "Application deployed successfully and health check passed"
      when: health_check.status == 200
