---
- name: Deploy Multi-Container Application
  hosts: target
  become: yes
  vars:
    project_dir: /opt/multi-container-service
    docker_registry: ""  # Add if using private registry

  tasks:
    - name: Ensure project directory exists
      file:
        path: "{{ project_dir }}"
        state: directory
        mode: '0755'

    - name: Copy project files
      synchronize:
        src: /home/{{ ansible_user }}/multi-container-service/
        dest: "{{ project_dir }}"
        delete: yes
        recursive: yes
      delegate_to: control

    - name: Copy environment file
      template:
        src: /home/{{ ansible_user }}/multi-container-service/.env
        dest: "{{ project_dir }}/.env"
        mode: '0600'
      delegate_to: control

    - name: Build and start containers
      docker_compose:
        project_src: "{{ project_dir }}"
        state: present
        pull: yes
        remove_orphans: yes
        build: yes

    - name: Prune unused Docker images
      docker_prune:
        images: yes
        images_filters:
          dangling: true

    - name: Check services health
      uri:
        url: "http://localhost/health"
        return_content: yes
      register: health_check
      until: health_check.status == 200
      retries: 12
      delay: 5

    - name: Show deployment status
      debug:
        msg: "Application deployed successfully. Health check response: {{ health_check.content }}"
